app.mock.onGet(/\/positions\/[0-9]+\/*$/).reply(200, JSON.stringify({
  position: {
    id: 4,
    title: 'مدیر عامل',
    position_id: 1,
    type: 'post',
    user_id: 5,
    enabled: null,
    shift_id: 43,
    deleted_at: null,
    created_at: '2016-12-07 14:52:57',
    updated_at: '2017-06-28 15:37:50',
    roles: [
      {
        id: 1,
        name: 'مدیر',
        display_name: 'مدیر',
        description: 'دسترسی های مدیر برنامه',
        created_at: null,
        updated_at: '2017-06-20 09:54:43',
        pivot: {
          position_id: 4,
          role_id: 1,
        },
        perms: [
          {
            id: 1,
            name: 'User@store',
            display_name: 'افزودن کاربر جدید',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 1,
            },
          },
          {
            id: 2,
            name: 'User@update',
            display_name: 'تصحیح کاربران',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 2,
            },
          },
          {
            id: 3,
            name: 'User@index',
            display_name: 'مشاهده لیست کاربران',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 3,
            },
          },
          {
            id: 4,
            name: 'User@destroy',
            display_name: 'حذف کاربران',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 4,
            },
          },
          {
            id: 5,
            name: 'Position@index',
            display_name: 'مشاهده چارت سازمانی',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 5,
            },
          },
          {
            id: 6,
            name: 'Position@store',
            display_name: 'افزودن آیتم به چارت سازمانی',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 6,
            },
          },
          {
            id: 7,
            name: 'Position@update',
            display_name: 'تغییر اطلاعات چارت سازمانی',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 7,
            },
          },
          {
            id: 8,
            name: 'Position@destroy',
            display_name: 'حذف آیتم از چارت سازمانی',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 8,
            },
          },
          {
            id: 9,
            name: 'Bank@index',
            display_name: 'مشاهده لیست بانک ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 9,
            },
          },
          {
            id: 10,
            name: 'Bank@store',
            display_name: 'افزودن بانک جدید',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 10,
            },
          },
          {
            id: 11,
            name: 'Bank@update',
            display_name: 'تصحیح اطلاعات بانک ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 11,
            },
          },
          {
            id: 12,
            name: 'Bank@destroy',
            display_name: 'حذف بانک',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 12,
            },
          },
          {
            id: 13,
            name: 'Calendar@index',
            display_name: 'مشاهده تقویم',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 13,
            },
          },
          {
            id: 14,
            name: 'Calendar@store',
            display_name: 'افزودن تقویم',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 14,
            },
          },
          {
            id: 15,
            name: 'Calendar@update',
            display_name: 'تغییر اطلاعات تقویم',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 15,
            },
          },
          {
            id: 16,
            name: 'Calendar@destroy',
            display_name: 'حذف تقویم',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 16,
            },
          },
          {
            id: 17,
            name: 'Company@index',
            display_name: 'مشاهده لیست شرکت ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 17,
            },
          },
          {
            id: 18,
            name: 'Company@store',
            display_name: 'افزودن شرکت',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 18,
            },
          },
          {
            id: 19,
            name: 'Company@update',
            display_name: 'تغییر اطلاعات شرکت',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 19,
            },
          },
          {
            id: 20,
            name: 'Company@destroy',
            display_name: 'حذف شرکت',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 20,
            },
          },
          {
            id: 21,
            name: 'Device@index',
            display_name: 'مشاهده لیست دستگاه ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 21,
            },
          },
          {
            id: 22,
            name: 'Device@store',
            display_name: 'افزودن دستگاه جدید',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 22,
            },
          },
          {
            id: 23,
            name: 'Device@update',
            display_name: 'تغییر اطلاعات دستگاه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 23,
            },
          },
          {
            id: 24,
            name: 'Device@destroy',
            display_name: 'حذف دستگاه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 24,
            },
          },
          {
            id: 25,
            name: 'Finger@store',
            display_name: 'افزودن اثر انگشت',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 25,
            },
          },
          {
            id: 26,
            name: 'Finger@destroy',
            display_name: 'حذف اثر انگشت',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 26,
            },
          },
          {
            id: 27,
            name: 'Group@index',
            display_name: 'مشاهده لیست گروه ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 27,
            },
          },
          {
            id: 28,
            name: 'Group@store',
            display_name: 'افزودن گروه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 28,
            },
          },
          {
            id: 29,
            name: 'Group@update',
            display_name: 'تغییر اطلاعات گروهی',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 29,
            },
          },
          {
            id: 30,
            name: 'Group@destroy',
            display_name: 'حذف گروه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 30,
            },
          },
          {
            id: 31,
            name: 'Role@index',
            display_name: 'مشاهده لیست دسترسی ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 31,
            },
          },
          {
            id: 32,
            name: 'Role@store',
            display_name: 'افزودن دسترسی جدید',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 32,
            },
          },
          {
            id: 33,
            name: 'Role@update',
            display_name: 'تغییر اطلاعات دسترسی ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 33,
            },
          },
          {
            id: 34,
            name: 'Role@destroy',
            display_name: 'حذف یک دسترسی',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 34,
            },
          },
          {
            id: 35,
            name: 'Rule@index',
            display_name: 'مشاهده لیست قانون ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 35,
            },
          },
          {
            id: 36,
            name: 'Rule@store',
            display_name: 'افزودن قانون جدید',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 36,
            },
          },
          {
            id: 37,
            name: 'Rule@update',
            display_name: 'تغییر اطلاعات یک قانون',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 37,
            },
          },
          {
            id: 38,
            name: 'Rule@destroy',
            display_name: 'حذف قانون',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 38,
            },
          },
          {
            id: 39,
            name: 'Request@index',
            display_name: 'مشاهده لیست درخواست ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 39,
            },
          },
          {
            id: 40,
            name: 'Request@store',
            display_name: 'افزودن درخواست جدید',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 40,
            },
          },
          {
            id: 41,
            name: 'Request@update',
            display_name: 'تغییر اطلاعات یک درخواست',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 41,
            },
          },
          {
            id: 42,
            name: 'Request@destroy',
            display_name: 'حذف درخواست',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 42,
            },
          },
          {
            id: 43,
            name: 'IOEvent@index',
            display_name: 'مشاهده ورود و خروج ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 43,
            },
          },
          {
            id: 44,
            name: 'IOEvent@store',
            display_name: 'افزودن ورود و خروج',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 44,
            },
          },
          {
            id: 45,
            name: 'IOEvent@destroy',
            display_name: 'حذف ورود و خروج',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 45,
            },
          },
          {
            id: 46,
            name: 'IOEvent@update',
            display_name: 'تغییر اطلاعات ورود و خروج',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 46,
            },
          },
          {
            id: 47,
            name: 'IOEvent@accept',
            display_name: 'تایید و یا رد کردن ورود و خروج',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 47,
            },
          },
          {
            id: 48,
            name: 'Writ@index',
            display_name: 'مشاهده لیست حکم ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 48,
            },
          },
          {
            id: 49,
            name: 'Writ@store',
            display_name: 'افزودن حکم جدید',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 49,
            },
          },
          {
            id: 50,
            name: 'Writ@update',
            display_name: 'تغییر اطلاعات حکم',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 50,
            },
          },
          {
            id: 51,
            name: 'Writ@destroy',
            display_name: 'حذف حکم',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 51,
            },
          },
          {
            id: 52,
            name: 'WorkingHour@index',
            display_name: 'مشاهده لیست ساعت کاری ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 52,
            },
          },
          {
            id: 53,
            name: 'WorkingHour@store',
            display_name: 'افزودن ساعت کاری',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 53,
            },
          },
          {
            id: 54,
            name: 'WorkingHour@update',
            display_name: 'تغییر اطلاعات ساعت کاری ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 54,
            },
          },
          {
            id: 55,
            name: 'WorkingHour@destroy',
            display_name: 'حذف ساعت کاری',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 55,
            },
          },
          {
            id: 56,
            name: 'Report@index',
            display_name: 'مشاهده گزارش',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 56,
            },
          },
          {
            id: 57,
            name: 'Report@store',
            display_name: 'افزودن گزارش',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 57,
            },
          },
          {
            id: 58,
            name: 'Report@update',
            display_name: 'تغییر اطلاعات گزارش',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 58,
            },
          },
          {
            id: 59,
            name: 'Report@destroy',
            display_name: 'حذف گزارش',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 59,
            },
          },
          {
            id: 60,
            name: 'Shift@index',
            display_name: 'مشاهده شیفت',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 60,
            },
          },
          {
            id: 61,
            name: 'Shift@store',
            display_name: 'افزودن شیفت',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 61,
            },
          },
          {
            id: 62,
            name: 'Shift@update',
            display_name: 'تغییر اطلاعات شیفت',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 62,
            },
          },
          {
            id: 63,
            name: 'Shift@destroy',
            display_name: 'حذف شیفت',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 63,
            },
          },
          {
            id: 64,
            name: 'Budget@index',
            display_name: 'مشاهده بودجه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 64,
            },
          },
          {
            id: 65,
            name: 'Budget@store',
            display_name: 'ذخیره بودجه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 65,
            },
          },
          {
            id: 66,
            name: 'Budget@update',
            display_name: 'تغییر اطلاعات بودجه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 66,
            },
          },
          {
            id: 67,
            name: 'Budget@destroy',
            display_name: 'حذف بودجه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 67,
            },
          },
          {
            id: 68,
            name: 'Settings@index',
            display_name: 'مشاهده تنظیمات',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 68,
            },
          },
          {
            id: 69,
            name: 'Settings@store',
            display_name: 'افزودن تنظیمات',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 69,
            },
          },
          {
            id: 70,
            name: 'Settings@update',
            display_name: 'تغییر اطلاعات تنظیمات',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 70,
            },
          },
          {
            id: 71,
            name: 'Settings@destroy',
            display_name: 'حذف تنظیمات',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 71,
            },
          },
          {
            id: 72,
            name: 'Rule@upload',
            display_name: 'آپلود قانون',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 72,
            },
          },
          {
            id: 78,
            name: 'RequestStatus@update',
            display_name: 'تغییر وضعیت یک درخواست',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 78,
            },
          },
          {
            id: 77,
            name: 'RequestStatus@index',
            display_name: 'مشاهده لیست وضعیت درخواست ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 77,
            },
          },
          {
            id: 76,
            name: 'RequestWorkflow@destroy',
            display_name: 'حذف روند درخواست',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 76,
            },
          },
          {
            id: 75,
            name: 'RequestWorkflow@update',
            display_name: 'تغییر اطلاعات یک روند درخواست',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 75,
            },
          },
          {
            id: 74,
            name: 'RequestWorkflow@store',
            display_name: 'افزودن روند درخواست جدید',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 74,
            },
          },
          {
            id: 73,
            name: 'RequestWorkflow@index',
            display_name: 'مشاهده لیست روند درخواست ها',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 73,
            },
          },
          {
            id: 79,
            name: 'Report@runForAll',
            display_name: 'گرفتن گزارش برای همه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 79,
            },
          },
          {
            id: 80,
            name: 'IOEvent@selfIndex',
            display_name: 'مشاهده اطلاعات تردد شخصی',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 80,
            },
          },
          {
            id: 83,
            name: 'Request@storeSubUser',
            display_name: 'درخواست برای افراد زیر مجموعه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 83,
            },
          },
          {
            id: 86,
            name: 'User@showDeleted',
            display_name: 'مشاهده لیست همه کاربران (حذف شده)',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 86,
            },
          },
          {
            id: 84,
            name: 'User@showSubUser',
            display_name: 'مشاهده لیست همه کاربران (زیر مجموعه)',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 84,
            },
          },
          {
            id: 85,
            name: 'User@showMe',
            display_name: 'مشاهده لیست همه کاربران (فقط خودش)',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 85,
            },
          },
          {
            id: 82,
            name: 'Report@forMe',
            display_name: 'گزارشگیری برای خود کاربر',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 82,
            },
          },
          {
            id: 81,
            name: 'Report@forSubUser',
            display_name: 'گزارشگیری برای همه کاربران زیر مجموعه',
            description: null,
            created_at: null,
            updated_at: null,
            pivot: {
              role_id: 1,
              permission_id: 81,
            },
          },
        ],
      },
    ],
    shift: {
      id: 43,
      name: 'شیفت آخر وقت 0',
      description: null,
      calendar_id: 19,
      created_at: '2017-05-27 15:40:41',
      updated_at: '2017-05-27 15:40:41',
    },
    user: {
      id: 5,
      personnel_id: '3',
      company_id: 1,
      insurance_id: null,
      first_name: 'سید مرتضی',
      last_name: 'پورحسینی',
      father_name: null,
      national_code: '1755766246',
      internal_line: null,
      birthday: null,
      birth_certificate_number: null,
      birth_place: null,
      birth_register_place: null,
      nationality: 'ایرانی',
      married: 1,
      gender: 'male',
      active: null,
      is_member: 1,
      email: 'pourhoseiny@jahangostarpars.com',
      address: null,
      identification_code: '3',
      card_number: null,
      allow_finger: 1,
      allow_card: 0,
      allow_code: 0,
      verify_card: 0,
      shift_id: null,
      deleted_at: null,
      created_at: '2016-12-07 11:45:53',
      updated_at: '2017-06-14 11:44:08',
      has_insurance: 0,
      profile: 'http://cloud.jgpr.ir/storage/pictures/5940e2407c6d7.jpg',
      military: null,
      education: null,
      recruitment: null,
      rate: null,
      leaving_date: null,
      leaving_reason: null,
      children: null,
      groups: [],
      phones: [],
      insurance: {
        id: 3,
        user_id: 5,
        insurance_type_id: 1,
        number: '12545444',
        created_at: '2017-05-08 14:09:44',
        updated_at: '2017-05-08 14:09:44',
      },
      financial_infos: [],
      contracts: [
        {
          id: 4,
          user_id: 5,
          recruitment_type_id: 1,
          begin_date: '2016-12-07',
          expire_date: '2016-12-07',
          rate: null,
          leaving_date: '2016-12-07',
          leaving_reason: null,
          has_insurance: 1,
          created_at: '2016-12-07 11:45:53',
          updated_at: '2017-06-14 11:44:10',
        },
      ],
      shift: null,
    },
  },
}));



app.mock.onPost(/\/positions\?acceptAll=true$/).reply(200, JSON.stringify({
  position: {
    title: 'مدیر2123 12321 gdgsg  عامل',
    parent: 1,
    id: 400,
    isActive: null,
    description: 'سید مرتضی ... پورحسینی',
    hasGroup: false,
    user_id: 400,
    avatar: 'http://cloud.jgpr.ir/storage/pictures/5940e2407c6d7.jpg',
    templateName: 'info',
  },
}));

app.mock.onPost('/positions').reply(200, JSON.stringify({
  confirm: {
    code: 200,
    msg: 'Confirm',
  },
}));

app.mock.onPut(/\/positions\/[0-9]+\/*$/).reply(200, JSON.stringify({
  confirm: {
    code: 200,
    msg: 'Confirm',
  },
}));

app.mock.onPut(/\/positions\/[0-9]+\?acceptAll=true*$/).reply(200, JSON.stringify({
  position: {
      title: 'مدیر  sdfsdfsdf عامل',
      parent: 1,
      id: 4,
      isActive: null,
      description: 'سید مرتضی پورحسینی',
      hasGroup: false,
      user_id: 5,
      avatar: 'http://cloud.jgpr.ir/storage/pictures/5940e2407c6d7.jpg',
      templateName: 'info',
    },
}));

app.mock.onDelete(/\/positions\/[0-9]*$/).reply(200, JSON.stringify({}));