import React from 'react';
import Gantt1 from './Gantt1';


const clockings=[
    {
        id: 7219,
        device_id: 1,                           // اگر نال بود یعنی بصورت دستی ثبت شده است و از دستگاه نیست
        user_id: 57,
        io_id: 'b71fc992',
        entry_type: 'in',                       //  نوع تردد ورود / خروج / اعلام حضور
        type_id: 144,                           // نوع تردد ماموریت - مرخصی - عادی
        datetime: '2018-06-10 08:59:40',        // تاریخ و ساعت تردد
        changed: 1,
        status: 'accepted',                     // وضعیت تردد
        description: null,                      // توضیحات تردد  − اگر دستی ثبت شد ممکن است توضیحات داشته باشد
        deleted_at: null,                       // ترددی که حذف شده باشد تاریخ دارد
        created_at: '2018-06-10 14:30:03',      // تاریخ ایجاد
        updated_at: '2018-06-10 14:30:03',      // تاریخ ویرایش − اگر تاریخ ایجاد و تاریخ ویرایش باهم فرق داشته باشند یعنی احتمالا یکی از مقادیر نوع تردد − وضعیت تردد - تاریخ تررد اصلاح شده
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null,
            }
        }
    },
    {
        id: 7220,
        device_id: 1,
        user_id: 57,
        io_id: 'd57ed555',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-06-10 10:28:40',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-06-10 14:30:03',
        updated_at: '2018-06-10 14:30:03',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 7256,
        device_id: 1,                           // اگر نال بود یعنی بصورت دستی ثبت شده است و از دستگاه نیست
        user_id: 57,
        io_id: 'b71fc992',
        entry_type: 'in',                       //  نوع تردد ورود / خروج / اعلام حضور
        type_id: 144,                           // نوع تردد ماموریت - مرخصی - عادی
        datetime: '2018-06-10 12:59:40',        // تاریخ و ساعت تردد
        changed: 1,
        status: 'accepted',                     // وضعیت تردد
        description: null,                      // توضیحات تردد  − اگر دستی ثبت شد ممکن است توضیحات داشته باشد
        deleted_at: null,                       // ترددی که حذف شده باشد تاریخ دارد
        created_at: '2018-06-10 14:30:03',      // تاریخ ایجاد
        updated_at: '2018-06-10 14:30:03',      // تاریخ ویرایش − اگر تاریخ ایجاد و تاریخ ویرایش باهم فرق داشته باشند یعنی احتمالا یکی از مقادیر نوع تردد − وضعیت تردد - تاریخ تررد اصلاح شده
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null,
            }
        }
    },
    {
        id: 7229,
        device_id: 1,
        user_id: 57,
        io_id: 'd57ed555',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-06-10 19:28:40',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-06-10 14:30:03',
        updated_at: '2018-06-10 14:30:03',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    /////neshan gharar dadan
    {
        id: 7200,
        device_id: 1,
        user_id: 57,
        io_id: '2eff6a48',
        entry_type: 'in',
        type_id: 147,
        datetime: '2018-06-09 11:16:27',
        changed: 1,
        status: 'waiting',
        description: null,
        deleted_at: null,
        created_at: '2018-06-09 23:30:03',
        updated_at: '2018-06-09 23:30:03',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },

    {
        id: 7162,
        device_id: 1,
        user_id: 57,
        io_id: '0458c2ad',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-06-09 17:54:53',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-06-03 23:30:04',
        updated_at: '2018-06-03 23:30:04',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },

    {
        id: 7133,
        device_id: 1,
        user_id: 57,
        io_id: '152531c9',
        entry_type: 'in',
        type_id: 147,
        datetime: '2018-06-03 10:17:46',
        changed: 1,
        status: 'waiting',
        description: null,
        deleted_at: null,
        created_at: '2018-06-03 23:30:04',
        updated_at: '2018-06-03 23:30:04',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 7097,
        device_id: 1,
        user_id: 57,
        io_id: 'e3737861',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-06-02 18:01:35',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-06-02 23:30:03',
        updated_at: '2018-06-02 23:30:03',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 7058,
        device_id: 1,
        user_id: 57,
        io_id: 'c603da3e',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-06-02 08:32:33',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-06-02 14:30:02',
        updated_at: '2018-06-02 14:30:02',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 7017,
        device_id: 1,
        user_id: 57,
        io_id: '12e57b73',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-30 18:23:34',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-30 23:30:05',
        updated_at: '2018-05-30 23:30:05',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6953,
        device_id: 1,
        user_id: 57,
        io_id: '3fe10a10',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-30 07:46:52',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-30 13:46:13',
        updated_at: '2018-05-30 13:46:13',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6940,
        device_id: 1,
        user_id: 57,
        io_id: 'fc83879f',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-29 18:58:08',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-29 23:30:04',
        updated_at: '2018-05-29 23:30:04',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6912,
        device_id: 1,
        user_id: 57,
        io_id: 'e9b42e95',
        entry_type: 'in',
        type_id: 147,
        datetime: '2018-05-29 11:06:49',
        changed: 1,
        status: 'waiting',
        description: null,
        deleted_at: null,
        created_at: '2018-05-29 18:43:48',
        updated_at: '2018-05-29 18:43:48',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6871,
        device_id: 1,
        user_id: 57,
        io_id: '1ec26bc0',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-28 18:02:35',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-28 23:30:05',
        updated_at: '2018-05-28 23:30:05',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6841,
        device_id: 1,
        user_id: 57,
        io_id: 'ca031843',
        entry_type: 'in',
        type_id: 147,
        datetime: '2018-05-28 10:48:07',
        changed: 1,
        status: 'waiting',
        description: null,
        deleted_at: null,
        created_at: '2018-05-28 23:30:05',
        updated_at: '2018-05-28 23:30:05',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6840,
        device_id: 1,
        user_id: 57,
        io_id: '229019a4',
        entry_type: 'out',
        type_id: 147,
        datetime: '2018-05-28 10:47:23',
        changed: 1,
        status: 'waiting',
        description: null,
        deleted_at: null,
        created_at: '2018-05-28 23:30:05',
        updated_at: '2018-05-28 23:30:05',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6753,
        device_id: 1,
        user_id: 57,
        io_id: '343d0d75',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-27 08:18:15',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-27 14:30:03',
        updated_at: '2018-05-27 14:30:03',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6734,
        device_id: 1,
        user_id: 57,
        io_id: 'ede16cdd',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-26 19:58:16',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-27 14:30:03',
        updated_at: '2018-05-27 14:30:03',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6676,
        device_id: 1,
        user_id: 57,
        io_id: '783eb862',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-26 07:59:58',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-26 14:20:48',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6637,
        device_id: 1,
        user_id: 57,
        io_id: '7812b54a',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-23 19:08:22',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-24 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6598,
        device_id: 1,
        user_id: 57,
        io_id: '1706c77c',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-23 09:07:43',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-23 14:30:02',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6561,
        device_id: 1,
        user_id: 57,
        io_id: 'd72431af',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-22 18:03:59',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-22 23:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6536,
        device_id: 1,
        user_id: 57,
        io_id: 'd5986b9d',
        entry_type: 'in',
        type_id: 147,
        datetime: '2018-05-22 10:54:47',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-22 23:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6493,
        device_id: 1,
        user_id: 57,
        io_id: 'bba67399',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-21 17:23:00',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-21 23:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6453,
        device_id: 1,
        user_id: 57,
        io_id: '872846bd',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-21 07:54:32',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-21 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6430,
        device_id: 1,
        user_id: 57,
        io_id: 'b3be040b',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-20 17:13:39',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-20 23:30:04',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6376,
        device_id: 1,
        user_id: 57,
        io_id: '84257550',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-20 07:26:37',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-20 14:30:04',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6368,
        device_id: 1,
        user_id: 57,
        io_id: 'e7320266',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-19 18:18:25',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-19 23:30:02',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6341,
        device_id: 1,
        user_id: 57,
        io_id: 'd55f8e2e',
        entry_type: 'in',
        type_id: 147,
        datetime: '2018-05-19 11:57:36',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-19 23:30:02',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6232,
        device_id: 1,
        user_id: 57,
        io_id: '164d9483',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-15 19:34:48',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-16 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6199,
        device_id: 1,
        user_id: 57,
        io_id: 'e554e460',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-15 08:53:00',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-15 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6162,
        device_id: 1,
        user_id: 57,
        io_id: '379dc1b7',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-14 19:51:50',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-15 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6123,
        device_id: 1,
        user_id: 57,
        io_id: '0259fd43',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-14 08:49:11',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-14 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6098,
        device_id: 1,
        user_id: 57,
        io_id: 'b9cc1ea3',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-13 19:33:34',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-14 13:16:00',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 6065,
        device_id: 1,
        user_id: 57,
        io_id: '63e2d8e6',
        entry_type: 'in',
        type_id: 147,
        datetime: '2018-05-13 10:46:57',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-13 23:30:05',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    /*
    {
        id: 6025,
        device_id: 1,
        user_id: 57,
        io_id: 'b1d46931',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-12 19:03:14',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-13 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },

    {
        id: 5962,
        device_id: 1,
        user_id: 57,
        io_id: 'ed973999',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-12 06:09:43',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-12 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5961,
        device_id: 1,
        user_id: 57,
        io_id: 'e2cd3bf6',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-12 03:37:09',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-12 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    */
    {
        id: 5954,
        device_id: 1,
        user_id: 57,
        io_id: '4989fd9f',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-11 14:33:19',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-11 23:30:02',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5941,
        device_id: 1,
        user_id: 57,
        io_id: 'e82b2456',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-09 18:33:29',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-09 23:30:05',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5905,
        device_id: 1,
        user_id: 57,
        io_id: '47e9dba7',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-09 08:58:11',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-09 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5883,
        device_id: 1,
        user_id: 57,
        io_id: '16ac1fb0',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-08 20:43:57',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-09 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5843,
        device_id: 1,
        user_id: 57,
        io_id: '19271e5b',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-08 08:50:17',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-08 14:30:04',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5817,
        device_id: 1,
        user_id: 57,
        io_id: '615a46ff',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-07 19:44:57',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-08 14:30:04',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5781,
        device_id: 1,
        user_id: 57,
        io_id: 'a878bebd',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-07 09:06:58',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-07 14:30:04',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5752,
        device_id: 1,
        user_id: 57,
        io_id: '3be6ac93',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-06 17:35:39',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-06 23:30:04',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5676,
        device_id: 1,
        user_id: 57,
        io_id: 'bffcc0a4',
        entry_type: 'in',
        type_id: 147,
        datetime: '2018-05-05 10:17:36',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-05 16:52:39',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5626,
        device_id: 1,
        user_id: 57,
        io_id: 'd97ceaa7',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-05-01 19:05:47',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-02 14:30:03',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5594,
        device_id: 1,
        user_id: 57,
        io_id: '2b7de347',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-05-01 09:14:39',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-01 14:30:04',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5563,
        device_id: 1,
        user_id: 57,
        io_id: 'e749b596',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-04-30 19:04:22',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-05-01 13:27:23',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5521,
        device_id: 1,
        user_id: 57,
        io_id: '33c156d0',
        entry_type: 'in',
        type_id: 144,
        datetime: '2018-04-30 08:34:07',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-04-30 14:30:04',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    },
    {
        id: 5494,
        device_id: 1,
        user_id: 57,
        io_id: 'ffc4b0b0',
        entry_type: 'out',
        type_id: 144,
        datetime: '2018-04-29 19:11:16',
        changed: 1,
        status: 'accepted',
        description: null,
        deleted_at: null,
        created_at: '2018-04-30 14:30:04',
        updated_at: '2018-05-26 18:20:49',
        user: {
            id: 57,
            name: null,
            email: 'j.shariati@jahangostarpars.com',
            deleted_at: null,
            created_at: null,
            updated_at: null,
            profile: {
                id: 57,
                user_id: 57,
                personnel_id: '352',
                company_id: 1,
                first_name: 'جواد ',
                last_name: 'شريعتي',
                national_code: '2250030863',
                father_name: 'قلي',
                birthday: '1990-08-15 00:00:00',
                birth_certificate_number: '2250030863',
                birth_place: 'قائمشهر',
                birth_register_place: 'سوادکوه',
                nationality: 'ایرانی',
                married: 1,
                sex: 'male',
                address: 'مازندارن − قائمهشر− خ سید نظام الدین − گلستان ۵۵ − بن بست دوم سمت راست',
                province_id: 0,
                city_id: 0,
                education: 2,
                military: 3,
                avatar: null,
                created_at: '2017-04-29 09:09:36',
                updated_at: '2018-03-14 11:12:29',
                deleted_at: null
            }
        }
    }
];
export default class GanttTest extends React.PureComponent {



    render() {
        return (
            <div>

                <Gantt1
                    startWork={10}
                    endWork={13}
                    type={'addi'}
                    _duration={'duration'}
                    startField={'start'}
                    clockings={clockings}

                />

            </div>
        );
    }
}

